### PR TITLE
add template matching project

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@yger
@evarol
@julienboussard

would you like to participate tpo this project ?

**Comment by yger** [comment]
I'm in!

**Comment by julienboussard** [comment]
In this project we'd implement yass template matching?

**Comment by samuelgarcia** [comment]
@julienboussard : yes it would be super to implement yass template matching.

**Comment by yger** [comment]
Hopefully this is just some copy/paste. The idea here is to have several engines to process the chunks, given a dictionary of templates. Ideally, everything will be modular such that each of these engines can be properly benchmarked (speed/accuracy/...). We already have 3 engines. The one from Spyking circus, from TDC, and one with OMP

**Review by alejoe91 — APPROVED** [review]

**Comment by alejoe91** [comment]
@julienboussard I added you to the project ;)

**Pull request merged**
